In [ ]:
#Q1)

In [101]:
#import the libraries
import pandas as pd
import scipy 
import numpy as np
from scipy import stats

In [102]:
data1=pd.read_csv("Cutlets.csv")

In [103]:
data1

Unit A  Unit B
0   6.8090  6.7703
1   6.4376  7.5093
2   6.9157  6.7300
3   7.3012  6.7878
4   7.4488  7.1522
5   7.3871  6.8110
6   6.8755  7.2212
7   7.0621  6.6606
8   6.6840  7.2402
9   6.8236  7.0503
10  7.3930  6.8810
11  7.5169  7.4059
12  6.9246  6.7652
13  6.9256  6.0380
14  6.5797  7.1581
15  6.8394  7.0240
16  6.5970  6.6672
17  7.2705  7.4314
18  7.2828  7.3070
19  7.3495  6.7478
20  6.9438  6.8889
21  7.1560  7.4220
22  6.5341  6.5217
23  7.2854  7.1688
24  6.9952  6.7594
25  6.8568  6.9399
26  7.2163  7.0133
27  6.6801  6.9182
28  6.9431  6.3346
29  7.0852  7.5459
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

In [104]:
stats.ttest_ind( data1['Unit A'],data1['Unit B'])

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [ ]:
#p value is high hence so we will accept H0 there is no significant difference in the diameters of Unit A and Unit B

In [ ]:
#Q.2)

In [26]:
df=pd.read_csv("LabTAT.csv")

In [27]:
df

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [29]:
import scipy.stats as stats
stats.f_oneway(df.iloc[:,0], df.iloc[:,1],df.iloc[:,2],df.iloc[:,3])
               

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [ ]:
#p value is less than alpha there are so we will reject H0

In [47]:
lab1=df['Laboratory 1'].mean()
lab2=df['Laboratory 2'].mean()
lab3=df['Laboratory 3'].mean()
lab4=df['Laboratory 4'].mean()
data=(lab1+lab2+lab3+lab4)
data

720.8605000000002

In [81]:
data/4

180.21512500000006

In [82]:
lab=lab1,lab2,lab3,lab4
lab

(178.36158333333339, 178.9029166666668, 199.91325000000003, 163.6827499999999)

In [83]:
#Q.3)

In [87]:
import seaborn as sns
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import chi2_contingency
import scipy.stats as stats

In [88]:
dataset=pd.read_csv("BuyerRatio.csv")
dataset

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [89]:
dataset_table=dataset.iloc[:,1:6]
dataset_table



East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [90]:
dataset_table.values


array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [91]:
#Observed Values
Observed_Values = dataset_table.values 

print("Observed Values :-\n",Observed_Values)

Observed Values :-
 [[  50  142  131   70]
 [ 435 1523 1356  750]]


In [92]:
val=stats.chi2_contingency(dataset_table)
val

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [93]:
Expected_Values=val[3]

In [94]:
no_of_rows=len(dataset_table.iloc[0:2,0])
no_of_columns=len(dataset_table.iloc[0,0:4])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)

Degree of Freedom:- 3


In [95]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]

In [96]:
print("chi-square statistic:-",chi_square_statistic)

chi-square statistic:- 1.5152956451130446


In [97]:
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

critical_value: 7.814727903251179


In [98]:
#p-value
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)
print('p-value:',p_value)

p-value: 0.6787446296467897
Significance level:  0.05
Degree of Freedom:  3
p-value: 0.6787446296467897


In [99]:
if chi_square_statistic>=critical_value:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")
    
if p_value<=alpha:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")

Retain H0,There is no relationship between 2 categorical variables
Retain H0,There is no relationship between 2 categorical variables


In [105]:
#Q.4)

In [106]:
data=pd.read_csv('Costomer+OrderForm.csv')
data

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [109]:
data['Phillippines'].value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [111]:
data['Indonesia'].value_counts()


Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [112]:
data['Malta'].value_counts()


Error Free    269
Defective      31
Name: Malta, dtype: int64

In [116]:
data['India'].value_counts()


Error Free    280
Defective      20
Name: India, dtype: int64

In [119]:
# Make a contingency table
obs=np.array([[271,267,269,280],[29,33,31,20]])
obs

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [120]:
val=stats.chi2_contingency(obs)
val

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [ ]:
#p value   is 0.277>0.0 5
#P is high so we accept H0 i.e percentage defective in all countries are equal interfaces#